title: Reuben Tamakloe, PhD
email: drtamakloe@kaist.ac.kr
#author:
#name: "Reuben Tamakloe"
#email: drtamakloe@uos.ac.kr
description: KAIST - Eco-Friendly Smart Vehicle Research Center (2026)
affiliation: KAIST - Eco-Friendly Smart Vehicle Research Center (2026)
show_downloads: false

#Theme setup
theme: minima



# Google Analytics
google_analytics: G-G58P7X4Y1K
google_analytics: G-5QZTXXTGW4


# Minima social links
linkedin_username: drtamakloe
instagram_username: drtamakloe
twitter_username: drtamakloe

